### ISSUE TITLE
AttributeError: type object 'KxgrLogs' has no attribute 'KXGR_INVALID_PARAMETER'

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/sugar#83]
```bash
Traceback (most recent call last):
  File "/home/xmn/mambaforge/envs/literev/bin/sugar", line 8, in <module>
    sys.exit(app())
  File "/home/xmn/mambaforge/envs/literev/lib/python3.9/site-packages/containers_sugar/cli.py", line 165, in app
    sugar = Sugar(args_cast, options_args, cmd_args)
  File "/home/xmn/mambaforge/envs/literev/lib/python3.9/site-packages/containers_sugar/sugar.py", line 531, in __init__
    super().__init__(args, options_args, cmd_args)
  File "/home/xmn/mambaforge/envs/literev/lib/python3.9/site-packages/containers_sugar/sugar.py", line 72, in __init__
    self._verify_args()
  File "/home/xmn/mambaforge/envs/literev/lib/python3.9/site-packages/containers_sugar/sugar.py", line 549, in _verify_args
    KxgrLogs.KXGR_INVALID_PARAMETER,
AttributeError: type object 'KxgrLogs' has no attribute 'KXGR_INVALID_PARAMETER'
```

**Comment by xmnlab** [comment]
fixed. thanks @joel5vega
